[package]
name = "eg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eg_derive = { path = "../eg_derive", optional = true }

[features]
derive = ["eg_derive"]
